Arb 27
martinalbrnz/arb-admin-pracc pull request #15
Opened 2023-12-22 21:29 UTC by camimai07

agregado el formulado productos
maquetado segun campos de la api
agregue el form al html productos

2023-12-22 23:02 UTC, Lazajs requested changes

2023-12-22 23:02 UTC, Lazajs commented on src/app/modules/products/components/form/form.component.html
> +            isActive: {{p.isActive}}
En realidad isActive no es visible en la UI. Es de utilidad en el backend pero deberiamos ignorarlo por ahora (siquiera hace falta enviarlo en el fetch)

2023-12-26 22:26 UTC, martinalbrnz commented on src/app/modules/products/components/form/form.component.html
Recién veo: Para poder interactuar con los valores, el punto del formulario es que el usuario pueda ingresar data para despues mandar a api

2023-12-27 14:38 UTC, camimai07 commented on src/app/modules/products/components/form/form.component.html
aaah ok ok, pensé que el usuario no interaccionaba derecto con este form

2023-12-27 21:25 UTC, camimai07 reviewed
adapte los cambios sugeridos

2023-12-27 22:17 UTC, MelinaFuch approved these changes

2023-12-27 22:45 UTC, Lazajs approved these changes
nice!

2023-12-27 22:46 UTC, Lazajs commented on src/app/modules/products/components/form/form.component.html
> por qué tendrían que haber inputs?

Perdon por no haber visto esto antes, entré varias veces a revisar pero se ve que lo pasé por alto

2023-12-27 23:34 UTC, merged